title: "Sunwoo (Sunny) Lee"
description: ""
theme: minima


url: "https://sunnylinguist.github.io"
baseurl: ""

# 네비게이션 메뉴 설정
navigation: 
  main:
    - title: "Home"
      url: /
    - title: "Research"
      url: /research/
    - title: "Teaching"
      url: /teaching/
    - title: "Miscellaneous"
      url: /misc/
