title: "Sunwoo (Sunny) Lee"
description: ""
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

url: "https://sunnylinguist.github.io"
baseurl: ""

# 네비게이션 메뉴 설정
navigation: 
  main:
    - title: "Home"
      url: /
    - title: "Research"
      url: /research/
    - title: "Teaching"
      url: /teaching/
    - title: "Miscellaneous"
      url: /misc/
